# @package _global_

data:
  tokenizer:
    is_clmbr: True
    is_remap_numerical_codes: True
    path_to_code_2_detail: /share/pi/nigam/mwornow/hf_ehr/cache/tokenizer_v8_clmbr/code_2_detail.json
    excluded_vocabs:
      - STANFORD_OBS