# @package _global_

data:
  tokenizer:
    path_to_code_2_detail: /share/pi/nigam/mwornow/hf_ehr/cache/tokenizer_v8/code_2_detail.json
    is_remap_numerical_codes: False
    is_remap_codes_to_desc: False
    excluded_vocabs:
      - STANFORD_OBS