# @package _global_

data:
  dataloader:
    max_length: 1024
    batch_size: 2

model:
  # Name of model to load
  name: hyena
  # Name/path to pass to HF.from_pretrained()
  hf_name: LongSafari/hyenadna-large-1m-seqlen-hf
  # Kwargs for ModelConfig
  config_kwargs:
    max_seq_len: ${data.dataloader.max_length}
    d_model: 128
    n_layer: 2
    #d_inner: ${eval:4 * ${.d_model}}


trainer:
  optimizer:
    # Learning rate
    lr: 2e-4
    weight_decay: 0.1

  scheduler:
    # Number of local steps (i.e. non-global) from `initial_lr` -> `trainer.optimizer.lr`
    num_warmup_steps: 40_000
    # Number of local steps (i.e. non-global) from `trainer.optimizer.lr` -> `final_lr`
    num_decay_steps: 4_000_000
