# @package _global_

data:
  dataloader:
    max_length: 1024

model:
  # Name of HF model to load
  name: gpt2
  # Name/path to pass to HF.from_pretrained()
  hf_name: gpt2
  # Kwargs for ModelConfig
  config_kwargs:
    n_positions: ${data.dataloader.max_length}
    n_layer: 12
    n_head: 12
    n_embd: 768

trainer:
  optimizer:
    # Learning rate
    lr: 2e-4

  scheduler:
    # Number of local steps (i.e. non-global) from `initial_lr` -> `trainer.optimizer.lr`
    num_warmup_steps: 40_000
    # Number of local steps (i.e. non-global) from `trainer.optimizer.lr` -> `final_lr`
    num_decay_steps: 4_000_000
    #initial_lr: 3e-6
    #final_lr: 3e-5