# @package _global_

model:
  # Name of model to load
  name: hyena
  # Name/path to pass to HF.from_pretrained()
  hf_name: LongSafari/hyenadna-large-1m-seqlen-hf
  # Kwargs for ModelConfig
  config_kwargs:
    max_seq_len: 1024
    d_model: 128
    n_layer: 2
    #d_inner: ${eval:4 * ${.d_model}}

data:
  dataloader:
    # Max number of codes to feed into model at once per patient.
    batch_size: 2
    max_length: ${model.config_kwargs.max_seq_len}

trainer:
  optimizer:
    # Learning rate
    lr: 2e-4
    weight_decay: 0.1

  scheduler:
    # Number of local steps (i.e. non-global) from `initial_lr` -> `trainer.optimizer.lr`
    num_warmup_steps: 40_000
    # Number of local steps (i.e. non-global) from `trainer.optimizer.lr` -> `final_lr`
    num_decay_steps: 4_000_000
